""" 配置文件 """
MYSQL_USERNAME = "root"
MYSQL_PASSWORD = "123456"
MYSQL_DATABASE = "inventory_system"
MYSQL_PORT = "3306"
MYSQL_IP = "localhost"
HOST_IP = "0.0.0.0"

HOST_PORT = 8002

# 单点登录桥接配置   SINGLE_SIGN_ON
SINGLE_SIGN_ON_IP = "http://192.168.43.244"
SINGLE_SIGN_ON_PORT = "8008"
SINGLE_SIGN_ON_BASE = SINGLE_SIGN_ON_IP+":"+SINGLE_SIGN_ON_PORT
SINGLE_SIGN_ON_USER = SINGLE_SIGN_ON_BASE+"/users"
SINGLE_SIGN_ON_CODE = SINGLE_SIGN_ON_BASE+"/code"

# 应用系统 APPLICATIONS
APPLICATIONS_IP = "http://192.168.43.244"
APPLICATIONS_PORT = "8001"
APPLICATIONS_BASE = APPLICATIONS_IP+":"+APPLICATIONS_PORT + '/v1/applications/'

# -------- redis 配置 ----------
REDIS_HOST: str = "localhost"
REDIS_PASSWORD: str = ""
REDIS_DB: int = 1
REDIS_PORT: int = 6379
